// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/signed-in": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forgot-password" | "/reset-password" | "/verify-email" | "/sign-in" | "/sign-up" | "/signed-in" | "/profile" | "/*";
  };
  "routes/_public.tsx": {
    id: "routes/_public";
    page: "/";
  };
  "routes/_public._index.tsx": {
    id: "routes/_public._index";
    page: "/";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/forgot-password" | "/reset-password" | "/verify-email" | "/sign-in" | "/sign-up";
  };
  "routes/_auth.forgot-password.tsx": {
    id: "routes/_auth.forgot-password";
    page: "/forgot-password";
  };
  "routes/_auth.reset-password.tsx": {
    id: "routes/_auth.reset-password";
    page: "/reset-password";
  };
  "routes/_auth.verify-email.tsx": {
    id: "routes/_auth.verify-email";
    page: "/verify-email";
  };
  "routes/_auth.sign-in.tsx": {
    id: "routes/_auth.sign-in";
    page: "/sign-in";
  };
  "routes/_auth.sign-up.tsx": {
    id: "routes/_auth.sign-up";
    page: "/sign-up";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/signed-in" | "/profile";
  };
  "routes/_app.signed-in.tsx": {
    id: "routes/_app.signed-in";
    page: "/signed-in";
  };
  "routes/_app.profile.tsx": {
    id: "routes/_app.profile";
    page: "/profile";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};